@startuml grading
actor 仿真工程师
仿真工程师 -> TADSim界面 : 选择(或编辑)地图 & 场景
仿真工程师 -> TADSim界面 : 可配置评测指标参数(可使用默认跳过该步骤)
仿真工程师 -> TADSim界面 : 可配置评测指标组中包含哪些指标(可使用默认跳过该步骤)
仿真工程师 -> TADSim界面 : 选择评测指标组(可使用默认跳过该步骤)
仿真工程师 -> TADSim界面 : 选择模块组，其中默认包含评测Grading模块(可使用默认跳过该步骤)
仿真工程师 -> TADSim界面 : 启动仿真任务
TADSim界面 -> TADSim进程 : 进程初始化
TADSim进程 -> Grading : 初始化 Grading 模块, 消息注册, 加载地图文件
Grading -> Grading : 功能初始化 (地图加载计算地图相关信息)

loop Step 循环
TADSim进程 -> Grading : 接收仿真过程中各个消息
Grading -> Grading : 读取地图缓存信息
Grading -> TADSim进程 : 发出评测消息 (包含是否结束仿真的指令)
end

TADSim进程 -> Grading : 场景结束，调用 stop, 生成日志文件, 评测结果json文件
仿真工程师 -> TADSim界面 : 查看评测结果报告
TADSim界面 -> TADSim进程 : 读取评测结果json文件, 基于json文件内容(已约定好)生成报告

@enduml
