/* Generated by S-function Builder */
#ifndef _BATTERY_SFUNCTION_BUS_H_
#define _BATTERY_SFUNCTION_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#  include "tmwtypes.h"
#else
#  include "rtwtypes.h"
#endif

#ifndef DEFINED_TYPEDEF_FOR_batt_in_
#  define DEFINED_TYPEDEF_FOR_batt_in_
typedef struct {
  real_T batt_curr_A;
  real_T batt_temp_K;
} batt_in;
#endif

#ifndef DEFINED_TYPEDEF_FOR_batt_out_
#  define DEFINED_TYPEDEF_FOR_batt_out_
typedef struct {
  real_T batt_volt_V;
  real_T batt_soc_null;
  real_T batt_pwr_W;
  real_T batt_loss_pwr_W;
} batt_out;
#endif

/* Read only - ENDS */

#endif
