/* Generated by S-function Builder */
#ifndef _FRONT_MOTOR_SFUNCTION_BUS_H_
#define _FRONT_MOTOR_SFUNCTION_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#  include "tmwtypes.h"
#else
#  include "rtwtypes.h"
#endif

#ifndef DEFINED_TYPEDEF_FOR_moter_in_
#  define DEFINED_TYPEDEF_FOR_moter_in_
typedef struct {
  real_T trq_cmd_Nm;
  real_T mot_spd_RPM;
  real_T batt_volt_V;
} moter_in;
#endif

#ifndef DEFINED_TYPEDEF_FOR_motor_out_
#  define DEFINED_TYPEDEF_FOR_motor_out_
typedef struct {
  real_T batt_curr_A;
  real_T mot_trq_Nm;
} motor_out;
#endif

/* Read only - ENDS */

#endif
