/* Generated by S-function Builder */
#ifndef _SOFTABS_SFUNCTION_BUS_H_
#define _SOFTABS_SFUNCTION_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#  include "tmwtypes.h"
#else
#  include "rtwtypes.h"
#endif

#ifndef DEFINED_TYPEDEF_FOR_Ctrl_Input_
#  define DEFINED_TYPEDEF_FOR_Ctrl_Input_
typedef struct {
  uint8_T acc_control_mode;
  uint8_T brake_control_mode;
  uint8_T steer_control_mode;
  real_T target_acc_m_s2;
  real_T request_torque;
  real_T brake_pressure_01;
  real_T steer_request_torque;
  real_T steer_cmd_rad;
  uint8_T gear_cmd__0N1D2R3P;
} Ctrl_Input;
#endif

#ifndef DEFINED_TYPEDEF_FOR_powecu_in_
#  define DEFINED_TYPEDEF_FOR_powecu_in_
typedef struct {
  real_T acc_feedback_m_s2;
  real_T eng_spd_rad_s;
  real_T batt_soc_0_1;
  real_T diff_trq_req_Nm;
  real_T slip_ratio[4];
  real_T veh_speed_vx;
  Ctrl_Input driver_input;
} powecu_in;
#endif

#ifndef DEFINED_TYPEDEF_FOR_powecu_out_
#  define DEFINED_TYPEDEF_FOR_powecu_out_
typedef struct {
  real_T pt_trq_cmd_Nm;
  real_T brake_pressure_0_1;
  real_T brake_pressure_Pa[4];
  real_T abs_flag[4];
  real_T throttle_01;
} powecu_out;
#endif

/* Read only - ENDS */

#endif
